version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"


volumes:
  postgres_data:
